### ISSUE TITLE
Broken Tutorial or is something missing? Redundant texture list problem.

### ISSUE THREAD

**Issue by MxOrbulent** [Luligabi1/ParticleExampleMod#1]
Minecraft 1.17.1

`Caused by: java.lang.IllegalStateException: Redundant texture list for particle mxorbulent_morebarrierblocks:red_barrier_particle
	at net.minecraft.client.particle.ParticleManager.loadTextureList(ParticleManager.java:277) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.particle.ParticleManager.method_18837(ParticleManager.java:228) ~[minecraft-project-@-merged-named.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more`

Texture:
\src\main\resources\assets\mxorbulent_morebarrierblocks\textures\particle\red_barrier_particle.png

JSON:
\src\main\resources\assets\mxorbulent_morebarrierblocks\particles\red_barrier_particle.json

Contents of JSON:
`{
  "textures": [
    "mxorbulent_morebarrierblocks:red_barrier_particle"
  ]
}`

in MoreBarrierBlocks:
`Registry.register(Registry.PARTICLE_TYPE, new Identifier("mxorbulent_morebarrierblocks", "red_barrier_particle"), RED_BARRIER_NOCOL_PARTICLE);`

Above the onInitialize() in Main:
`public static final DefaultParticleType RED_BARRIER_NOCOL_PARTICLE = FabricParticleTypes.simple();`

In MoreBarrierBlocksClient:
`ClientSpriteRegistryCallback.event(PlayerScreenHandler.BLOCK_ATLAS_TEXTURE).register(((atlasTexture, registry) -> {
            registry.register(new Identifier("mxorbulent_morebarrierblocks", "particle/red_barrier_particle"));
        }));
        ParticleFactoryRegistry.getInstance().register(MoreBarrierBlocks.RED_BARRIER_NOCOL_PARTICLE, new RedBarrierNoColParticle.BarrierFactory());`

And yes the client tag thing is added to fabric.mod.json
Is the tutorial broken or am I missing something?

**Comment by MxOrbulent** [comment]
'Tis I who are broken.
Derped out and did not properly do my factories. Closing it as the tutorial is correct, don't try to use custom factories with this tutorial, it will blow up in your face.
